import {ArrowUpLeft, Check, ClipboardList, CalendarDays, ShieldCheck, Headset, Layers, Building2} from 'lucide-react';
import type {Language} from './i18n';
const copy={
 ar:{
 intro:'فكرتنا',title:'التوريد جزء من نجاح التشغيل.',lead:'التعامل مع موردين متعددين يعني أسعاراً متفرقة، ومواعيد مختلفة، ومتابعات لا تنتهي. تأسست فكرة ONEVA حول احتياج بسيط: أن تجد أعمالك مصدراً منظّماً يجمع احتياجاتها، وشريكاً مسؤولاً عن متابعة التفاصيل.',body:'نربط اختيار المنتجات بالمواصفات والكميات ومعدل الاستهلاك الفعلي. لذلك لا تبدأ علاقتنا بكتالوج وتنتهي بتسليم؛ بل تبدأ بفهم طريقة عملك، ثم بناء ترتيبات توريد تناسبها وتستمر معها.',mission:'رسالتنا',missionBody:'تبسيط المشتريات اليومية للشركات، من خلال تجميع الاحتياجات في علاقة توريد واضحة تجمع جودة متسقة، وقيمة تعاقدية، ومتابعة مسؤولة.',vision:'رؤيتنا',visionBody:'أن نتطور من مورد للمنتجات إلى شريك متكامل للمشتريات والتوريد، يتوسع مع احتياجات الشركات ويجعل إدارة الإمداد أكثر تنظيماً ووضوحاً.',
 services:'خدماتنا',servicesTitle:'أكثر من توفير منتج.',servicesLead:'ندير تفاصيل العلاقة بين احتياجك اليومي وخطة توريد يمكن لفريقك الاعتماد عليها.',
 cards:[['تجميع المشتريات','العطارة والحبوب والمنتجات الطازجة ومستلزمات التعبئة في علاقة واحدة. نجمع الفئات المتكررة لتقليل تعدد الطلبات وجهد التنسيق والمتابعة.','فئات متعددة · نقطة طلب واحدة'],['تحديد المواصفات','نتفق على نوع المنتج والمنشأ المطلوب والتعبئة والكميات ومعايير القبول قبل التوريد، لتكون توقعات فريقك واضحة في كل طلب متكرر.','متطلبات واضحة · جودة قابلة للمتابعة'],['عروض أسعار واتفاقات توريد','نعد العرض وفق حجم الطلب وتكراره وتنوع الأصناف. ويمكن أن تعكس الشروط التجارية مدة العلاقة ومواعيد السداد وطبيعة التشغيل، بحسب الاتفاق.','تسعير حسب الاحتياج · شروط متفق عليها'],['التوريد الدوري والمجدول','ننسّق دورات توريد يومية أو أسبوعية أو دورية وفق الاستهلاك والاتفاق، لتتمكن فرق المطبخ والمخزن والمشتريات من التخطيط بوضوح.','جدول مناسب · طلبات متكررة'],['تخطيط توافر الأصناف','نراجع الاحتياجات الأساسية والمتكررة، ونناقش البدائل المناسبة عند الحاجة. الهدف هو تقليل أثر نقص الأصناف على تشغيلك اليومي.','تخطيط للاحتياجات · بدائل بالموافقة'],['إدارة الحساب والمتابعة','للعملاء الرئيسيين نقطة تواصل مسؤولة تتابع الطلبات والأسعار والملاحظات والعقود وخطة التوريد، وتربط تفاصيل كل طلب بالصورة الكاملة لأعمالك.','تواصل واضح · مسؤولية محددة']],
 industries:'القطاعات التي نخدمها',industriesTitle:'كل نشاط له إيقاعه. ونحن نفهم الفرق.',industriesLead:'نوجّه خدماتنا للمؤسسات التي تعتمد أعمالها على استمرارية التوريد، ونرتّب المتطلبات وفق طبيعة كل نشاط.',
 sectors:[['المطاعم وسلاسل المطاعم','احتياجات متكررة ومواصفات موحّدة بين الفروع، مع ترتيب الطلبات وفق حجم التشغيل.'],['الفنادق والمنتجعات','توريد يدعم المطابخ وخدمات الضيافة، مع مراعاة تنوع الاستهلاك ومواعيد التشغيل.'],['الكاترينج والمطابخ المركزية','كميات تشغيلية ومواصفات تعبئة مناسبة للإنتاج الغذائي والطلبات كبيرة الحجم.'],['المستشفيات والمراكز الصحية','تنسيق الاحتياجات الغذائية والتشغيلية وفق مواصفات ومتطلبات المؤسسة المتفق عليها.'],['المدارس والجامعات','تنظيم احتياجات التغذية والتشغيل في المؤسسات التعليمية العامة والخاصة.'],['الشركات والمؤسسات متعددة الفروع','تجميع احتياجات المواقع وتنسيق التوريد من خلال علاقة واحدة قابلة للتوسع.']],
 quality:'الجودة في كل مرة',qualityTitle:'المعيار يُتفق عليه قبل وصول الطلب.',qualityBody:'الجودة المتسقة تبدأ من تعريف واضح لما يحتاجه العميل. نربط التوريد بمواصفات المنتج ومعايير الاستلام، ثم نتابع الملاحظات حتى تظل الطلبات المتكررة متوافقة مع الاتفاق.',qualityPoints:['تحديد المواصفات والتعبئة المطلوبة.','مراجعة الجودة ضمن خطوات تجهيز الطلب.','متابعة ملاحظات الاستلام والعمل على حلها.','مراجعة الاحتياجات قبل إعادة الطلب.'],
 account:'علاقة واحدة. متابعة متكاملة.',accountTitle:'شخص يفهم احتياجات تشغيلك.',accountBody:'مدير الحساب هو حلقة الوصل للعميل الرئيسي: يتابع تفاصيل الطلب الحالي، واحتياجات التوريد المتكرر، والشروط التجارية، والملاحظات التي تحتاج إلى حل. بهذه الطريقة لا تبدأ شرح احتياجاتك من جديد في كل مرة.',accountPoints:['الطلبات والاحتياجات المتكررة','الأسعار والشروط التجارية','ملاحظات الخدمة وحل المشكلات','العقود والتخطيط وتقارير المشتريات'],
 value:'لماذا ONEVA؟',valueTitle:'القيمة أبعد من سعر الفاتورة.',values:[['وقت أقل في التنسيق','علاقة واحدة تقلل تكرار التواصل والمتابعة بين موردين مختلفين.'],['رؤية أوضح للمشتريات','تنظيم الطلبات والفواتير والاحتياجات المتكررة يساعد فريقك على متابعة ما يحتاجه.'],['خطة تناسب الاستهلاك','مواعيد وكميات تُبنى حول واقع تشغيلك، بدلاً من قرارات الشراء في اللحظة الأخيرة.'],['علاقة تنمو معك','من موقع واحد إلى عدة فروع، نطوّر نطاق التوريد وفق احتياجات أعمالك والاتفاق.']],cta:'ناقش احتياجات شركتك',catalog:'تصفّح الكتالوج'
 },
 en:{
 intro:'THE IDEA BEHIND ONEVA',title:'Better supply supports better operations.',lead:'Multiple suppliers can mean separate prices, different delivery promises and endless follow-ups. ONEVA is built around a simple need: one organized source for your business essentials, with a partner accountable for the details.',body:'We connect product selection with specifications, quantities and actual consumption. Our relationship goes beyond a catalog and a delivery. It starts with understanding your operation, then shaping supply arrangements around the way it works.',mission:'Our mission',missionBody:'To simplify everyday business procurement through one clear supply relationship that combines consistent quality, contracted value and accountable support.',vision:'Our vision',visionBody:'To grow from a product supplier into an integrated procurement and supply partner, expanding with business needs and making supply management more organized and transparent.',
 services:'OUR SERVICES',servicesTitle:'More than sourcing a product.',servicesLead:'We connect your everyday requirements with a supply plan your team can work around.',
 cards:[['Consolidated procurement','Spices, grains, fresh produce and packaging through one relationship. We bring recurring categories together to reduce separate orders, coordination and follow-up.','Multiple categories · One ordering relationship'],['Specification planning','We agree on product type, required origin, packaging, quantities and acceptance criteria before supply, so your team knows what to expect with every repeat order.','Clear requirements · Consistent standards'],['Quotations & supply agreements','Quotations reflect volume, frequency and category mix. Commercial terms can also reflect the relationship duration, payment arrangements and operational requirements, as agreed.','Requirement-based pricing · Agreed terms'],['Scheduled & recurring supply','We coordinate daily, weekly or periodic supply cycles around consumption and your agreement, helping kitchen, warehouse and procurement teams plan ahead.','Suitable schedules · Recurring orders'],['Availability planning','We review core and recurring requirements and discuss suitable alternatives when needed. The aim is to reduce the operational impact of product shortages.','Demand planning · Approved alternatives'],['Account management & support','Major clients have an accountable contact for orders, pricing, feedback, contracts and supply planning, connecting each request with the broader needs of their business.','Clear communication · Defined accountability']],
 industries:'WHO WE SERVE',industriesTitle:'Every operation has its own rhythm.',industriesLead:'We serve organizations that depend on supply continuity, organizing requirements around the way each business operates.',
 sectors:[['Restaurants & restaurant groups','Recurring requirements and consistent specifications across branches, with orders organized around operational volume.'],['Hotels & resorts','Supply for kitchens and hospitality services, taking varied consumption and operating schedules into account.'],['Catering & central kitchens','Operational quantities and suitable packaging specifications for food production and high-volume requirements.'],['Hospitals & healthcare centers','Coordination of food and operational requirements around the institution’s agreed specifications and needs.'],['Schools & universities','Organized foodservice and operational requirements for public and private educational institutions.'],['Corporate & multi-branch businesses','Consolidated site requirements and coordinated supply through one scalable relationship.']],
 quality:'CONSISTENCY IN EVERY ORDER',qualityTitle:'The standard is agreed before delivery.',qualityBody:'Consistent quality starts with a clear definition of what the customer needs. We connect supply with product specifications and acceptance criteria, then follow up on feedback to keep recurring orders aligned with the agreement.',qualityPoints:['Define required specifications and packaging.','Include quality checks in order preparation.','Follow up on receiving feedback and resolve issues.','Review requirements before reordering.'],
 account:'ONE RELATIONSHIP. COMPLETE FOLLOW-UP.',accountTitle:'A person who understands your operation.',accountBody:'For major clients, the account manager connects today’s order with recurring requirements, commercial terms and service issues. Your needs remain part of one ongoing conversation, rather than starting from scratch with every request.',accountPoints:['Orders and recurring requirements','Pricing and commercial terms','Service feedback and issue resolution','Contracts, planning and purchasing reports'],
 value:'WHY ONEVA?',valueTitle:'Value beyond the invoice.',values:[['Less time coordinating','One relationship reduces repetitive communication and follow-up across different suppliers.'],['Clearer purchasing visibility','Organized orders, invoices and recurring requirements help your team understand what it needs.'],['A plan around consumption','Schedules and quantities shaped around your operation, reducing last-minute sourcing decisions.'],['A relationship that grows with you','From one location to multiple branches, supply coverage develops around your needs and agreement.']],cta:'Discuss your business needs',catalog:'Explore the catalog'
 }
};
export default function CompanyProfile({language,onContact}:{language:Language;onContact:()=>void}){
 const c=copy[language];const icons=[Layers,ClipboardList,Building2,CalendarDays,ShieldCheck,Headset];
 return <div className="company-profile">
 <section className="section container profile-story"><div><div className="eyebrow dark">{c.intro}</div><h2>{c.title}</h2><p className="profile-lead">{c.lead}</p><p>{c.body}</p></div><div className="purpose-panels"><div><span>01</span><h3>{c.mission}</h3><p>{c.missionBody}</p></div><div><span>02</span><h3>{c.vision}</h3><p>{c.visionBody}</p></div></div></section>
 <section className="profile-services section" id="services"><div className="container"><div className="section-heading"><div><div className="eyebrow dark">{c.services}</div><h2>{c.servicesTitle}</h2></div><p>{c.servicesLead}</p></div><div className="service-grid">{c.cards.map(([title,body,detail],i)=>{const Icon=icons[i];return <article className="service-card" key={i}><div className="service-top"><Icon size={27}/><span>0{i+1}</span></div><h3>{title}</h3><p>{body}</p><small>{detail}</small></article>;})}</div></div></section>
 <section className="section container" id="industries"><div className="section-heading"><div><div className="eyebrow dark">{c.industries}</div><h2>{c.industriesTitle}</h2></div><p>{c.industriesLead}</p></div><div className="industry-grid">{c.sectors.map(([title,body],i)=><div className="industry-item" key={i}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></div>)}</div></section>
 <section className="profile-standards"><div className="container standards-grid"><div><ShieldCheck size={36}/><div className="eyebrow">{c.quality}</div><h2>{c.qualityTitle}</h2><p>{c.qualityBody}</p><ul>{c.qualityPoints.map(p=><li key={p}><Check size={18}/>{p}</li>)}</ul></div><div><Headset size={36}/><div className="eyebrow">{c.account}</div><h2>{c.accountTitle}</h2><p>{c.accountBody}</p><ul>{c.accountPoints.map(p=><li key={p}><Check size={18}/>{p}</li>)}</ul></div></div></section>
 <section className="section container profile-value"><div className="section-heading"><div><div className="eyebrow dark">{c.value}</div><h2>{c.valueTitle}</h2></div></div><div className="value-grid">{c.values.map(([title,body],i)=><div key={i}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></div>)}</div><div className="profile-actions"><button className="button green" onClick={onContact}>{c.cta}<ArrowUpLeft size={20}/></button><a className="text-link" href="#shop">{c.catalog}<ArrowUpLeft size={20}/></a></div></section>
 </div>;
}
