import {products,categories} from './products';
export type Language='ar'|'en';
export const english:Record<string,string>={
 'من نحن':'About us',
 'تمت إضافة':'Added','لطلبك':'to your request','مرحباً ONEVA، أود الاستفسار عن خدمات التوريد وعروض الأسعار.':'Hello ONEVA, I would like to enquire about your supply services and quotations.',
 'سيتم تفعيل التواصل قريباً. رقم واتساب لم يُضف بعد.':'Contact will be available soon. The WhatsApp number has not been configured yet.',
 'استقبال الطلبات غير مفعّل حالياً. يُرجى المحاولة بعد إضافة رقم واتساب الخاص بالشركة.':'Requests are not available yet. Please try again once the company WhatsApp number has been added.',
 'انتقل للمحتوى':'Skip to content','شريك واحد، قيمة واحدة.':'one Vendor one Value','ONEVA الرئيسية':'ONEVA home','القائمة الرئيسية':'Main navigation','الرئيسية':'Home','عن ONEVA':'About ONEVA','قطاعات التوريد':'Supply sectors','المنتجات':'Products','كيف نعمل':'How it works','سلة الطلب،':'Request basket,','وحدة':'unit','طلبك':'Your request','القائمة':'Menu',
 'توريد منظّم. أعمال مستمرة.':'Organized supply. Business continuity.','كل احتياجاتك.':'Every need.','شريك':'One','واحد.':'partner.',
 'من المواد الغذائية إلى مستلزمات التشغيل، نجمع احتياجات أعمالك في مكان واحد. جودة ثابتة وتوريد منتظم، لتتفرّغ لما تصنعه أفضل.':'From food products to everyday operational supplies, we bring your business needs together. Consistent quality and reliable supply, so you can focus on what you do best.',
 'تصفّح المنتجات':'Browse products','تعرّف على ONEVA':'Meet ONEVA','جودة بمواصفات واضحة':'Clearly defined quality','توريد حسب احتياجك':'Supply around your needs','مشهد توضيحي لتوريد منتجات متنوعة وتجهيز الشحنات':'Illustrative scene of varied products and shipment preparation','مختارة بعناية لأعمالك':'Carefully selected for your business','جودة تبدأ من المصدر.':'Quality starts at the source.',
 'نلبّي احتياجات':'Serving','المطاعم':'Restaurants','الفنادق والمنتجعات':'Hotels & resorts','شركات الكاترينج':'Catering companies','المؤسسات':'Institutions','المطابخ المركزية':'Central kitchens','مجالات التوريد':'OUR SUPPLY CATEGORIES','احتياجات متنوعة.':'Many needs.','مصدر واحد.':'One source.','أربع فئات أساسية، تحت مظلة توريد واحدة.':'Four essential categories. One supply relationship.','اختر ما يحتاجه عملك ودع الباقي علينا.':'Choose what your business needs. We handle the rest.','منتج':'products','رمز ONEVA':'ONEVA brand mark',
 'شريك في تشغيل أعمالك،':'Your operational partner,','من أول طلب.':'from the first order.',
 'ONEVA شركة مصرية متخصصة في المشتريات والتوريد التشغيلي للشركات. نختصر تشتّت التعامل مع موردين متعددين في علاقة واحدة منظّمة، تجمع الجودة والقيمة والمتابعة.':'ONEVA is an Egypt-based B2B procurement and operational supply company. We replace the complexity of multiple suppliers with one organized relationship, bringing quality, value and accountable support together.',
 'مواصفات واضحة قبل التوريد':'Specifications agreed before supply','أسعار تناسب حجم أعمالك':'Pricing that reflects your volume','مواعيد توريد متفق عليها':'Agreed delivery schedules','نقطة تواصل واحدة':'One accountable point of contact',
 'كتالوج المنتجات':'PRODUCT CATALOG','اختياراتك. بداية طلبك.':'Your selection. Your next supply.','اختر المنتجات والكميات':'Choose products and quantities','واطلب عرض سعر عبر واتساب':'Request a quote on WhatsApp','فئات المنتجات':'Product categories','كل المنتجات':'All products','٤١':'41','ابحث عن منتج...':'Search products...','ابحث عن منتج':'Search products','مسح البحث':'Clear search','عرض':'Showing','الأسعار حسب الكمية والمواصفات':'Pricing depends on quantity and specifications','مضاف للطلب':'Added to request','الكمية والتعبئة حسب احتياجك':'Quantity and packing to suit your needs','حسب عرض السعر':'Price on request','زيادة':'Increase','تقليل':'Decrease','أضف للطلب':'Add to request','لم نجد منتجاً بهذا الاسم':'No matching products','جرّب كلمة أخرى أو تصفّح كل المنتجات.':'Try another search or browse all products.','عرض كل المنتجات':'View all products',
 'الصور توضيحية. يتم تأكيد المنشأ والمواصفات والتعبئة والتوفّر عند إعداد عرض السعر.':'Images are illustrative. Origin, specifications, packaging and availability are confirmed with your quotation.',
 'من الاختيار إلى التوريد':'FROM SELECTION TO SUPPLY','طلبك أبسط مما تتخيّل.':'Simple steps. Seamless supply.','خطوات واضحة، وفريق يتابع معك التفاصيل.':'A clear process, with our team by your side.','اختر احتياجاتك':'Choose your products','تصفّح الكتالوج وأضف الأصناف والكميات إلى طلبك.':'Browse the catalog and add products and quantities to your request.','أرسل على واتساب':'Send on WhatsApp','راجع طلبك وأضف تفاصيل أعمالك وأي مواصفات خاصة.':'Review your request and add your business details and requirements.','استلم عرض السعر':'Receive your quote','نراجع معك الكميات والمواصفات والتوفّر والتكلفة.':'We confirm quantities, specifications, availability and pricing with you.','نتفق ونورّد':'Agree and deliver','نؤكد تفاصيل الطلب وجدول التوريد المناسب لتشغيلك.':'Together, we agree on the order and a delivery schedule that fits your operation.',
 'نبدأ علاقة توريد أفضل':'LET’S BUILD A BETTER SUPPLY RELATIONSHIP','خلّي تركيزك على أعمالك.':'Focus on your business.','واحتياجاتك علينا.':'Leave the supply to us.','طلب واحد أو توريد دوري، نتحدث معك لنفهم ما تحتاجه.':'A one-off request or recurring supply: let’s talk about what you need.','تحدث مع فريق ONEVA':'Talk to the ONEVA team','شريكك للمشتريات والتوريد التشغيلي في مصر.':'Your procurement and operational supply partner in Egypt.','عن الشركة':'About us','تواصل معنا':'Contact us','ONEVA. جميع الحقوق محفوظة.':'ONEVA. All rights reserved.',
 'مراجعة طلبك':'Review your request','أصناف':'items','عرض سعر مخصص لأعمالك':'A QUOTE TAILORED TO YOUR BUSINESS','طلب التوريد':'Supply request','إغلاق الطلب':'Close request','راجع الكميات وأرسل طلبك. سيؤكد فريقنا الأسعار والتوفّر معك عبر واتساب.':'Review your quantities and send your request. Our team will confirm pricing and availability on WhatsApp.','زيادة كمية':'Increase quantity of','كمية':'Quantity of','تقليل كمية':'Decrease quantity of','حذف':'Remove','تفاصيل إضافية':'Additional details','اختياري':'Optional','اسمك':'Your name','الاسم':'Name','اسم الشركة أو النشاط':'Company or business name','اسم المطعم، الفندق أو الشركة':'Restaurant, hotel or company name','ملاحظات الطلب':'Request notes','مكان التوريد، الموعد المطلوب، أو مواصفات وتعبئة خاصة...':'Delivery location, preferred date, special specifications or packaging...','طلبك يبدأ باختيارك':'Your request starts here','أضف المنتجات التي يحتاجها عملك من الكتالوج.':'Add the products your business needs from the catalog.','إرسال الطلب عبر واتساب':'Send request on WhatsApp','طلب عرض سعر فقط — يتم تأكيد الطلب بعد الاتفاق.':'Quotation request only — orders are confirmed after agreement.',
 'العطارة والأعشاب':'Spices & herbs','نكهات أصيلة، ومواصفات ثابتة.':'Authentic flavors. Consistent specifications.','البقوليات والحبوب':'Pulses & grains','البقوليات':'Pulses & grains','أساسيات مطبخك، من مصادر مختارة.':'Kitchen essentials from selected sources.','الخضروات والفواكه الطازجة':'Fresh vegetables & fruit','الخضروات والفواكه':'Fresh produce','اختيارات طازجة لاحتياجاتك اليومية.':'Fresh selections for your everyday needs.','المستهلكات والتعبئة والتغليف':'Consumables & packaging','التعبئة والتغليف':'Packaging','كل ما يُكمل دورة تشغيل أعمالك.':'The supplies that complete your operation.',
 'كمون مصري':'Egyptian cumin','مصر':'Egypt','فلفل أسود برازيلي':'Brazilian black pepper','البرازيل':'Brazil','فلفل أسود فيتنامي':'Vietnamese black pepper','فيتنام':'Vietnam','كزبرة سوري':'Syrian coriander','سوريا':'Syria','حبهان جواتيمالي':'Guatemalan cardamom','جواتيمالا':'Guatemala','جوز الطيب سيرلانكي':'Sri Lankan nutmeg','سريلانكا':'Sri Lanka','قرنفل سيرلانكي':'Sri Lankan cloves','شطة مصري':'Egyptian chili powder','زر ورد باكستاني':'Pakistani rosebuds','باكستان':'Pakistan','قرفة سيجار إندونيسي':'Indonesian cinnamon sticks','إندونيسيا':'Indonesia','ملح صيني':'Monosodium glutamate (MSG)','عطارة':'Spices','زعتر سوري':'Syrian thyme','ثوم بودر':'Garlic powder','بصل بودر':'Onion powder','بذور الشيا':'Chia seeds','بذور':'Seeds','بذور الكتان':'Flax seeds','بذور اليقطين':'Pumpkin seeds',
 'فاصوليا بيضاء':'White beans','بقوليات':'Pulses','لوبيا':'Black-eyed peas','فول تدميس':'Fava beans','أرز أبيض عريض':'Short-grain white rice','حبوب':'Grains','أرز بسمتي هندي':'Indian basmati rice','الهند':'India','حمص':'Chickpeas','طماطم':'Tomatoes','طازج':'Fresh','بصل أبيض':'White onions','بصل أحمر':'Red onions','ليمون':'Lemons','كرنب أحمر':'Red cabbage','كرنب أبيض':'White cabbage','فلفل ألوان':'Mixed bell peppers',
 'شاليموه سوستة ألوان رفيع كرنو':'Karno slim colored bendy straws','كرتونة':'carton','٢٠ كيس × ١٠٠ قطعة':'20 bags × 100 pieces','شاليموه سوبر ألوان كرنو ٢٠٠ جم':'Karno super colored straws, 200 g','٢٠ كيس × ١٥٠ قطعة':'20 bags × 150 pieces','بولة آيس كريم مقاس ١':'Ice cream bowl, size 1','مقاس ١':'Size 1','بولة آيس كريم مقاس ٢':'Ice cream bowl, size 2','مقاس ٢':'Size 2','أكواب بلاستيك شفافة ١٠ أونز':'Clear plastic cups, 10 oz','١٠٠٠ قطعة':'1,000 pieces','غطاء بلاستيك شفاف ١٠ أونز':'Clear plastic lids, 10 oz','أكواب بلاستيك شفافة ١٢ أونز':'Clear plastic cups, 12 oz','غطاء بلاستيك شفاف ١٢ أونز':'Clear plastic lids, 12 oz','ستيك خشب كرنو':'Karno wooden stirrers','جوانتي شفاف':'Transparent gloves','مستهلكات':'Consumables','جوانتي جلد':'Leather gloves','كجم':'kg',
 'مرحباً ONEVA، أود طلب عرض سعر للأصناف التالية:':'Hello ONEVA, I would like a quotation for the following items:','الاسم:':'Name:','الشركة / النشاط:':'Company / business:','ملاحظات:':'Notes:','يرجى تأكيد الأسعار والتوفّر والمواصفات وموعد التوريد.':'Please confirm pricing, availability, specifications and delivery date.'
};
export function translate(text:string,language:Language):string{if(language==='ar')return text;const key=text.trim();return english[key]===undefined?text:text.replace(key,english[key]);}
export function getProducts(language:Language){return products.map(p=>({...p,name:translate(p.name,language),origin:translate(p.origin,language),unit:translate(p.unit,language),pack:p.pack?translate(p.pack,language):undefined}));}
export function getCategories(language:Language){return categories.map(c=>({...c,name:translate(c.name,language),short:translate(c.short,language),description:translate(c.description,language)}));}
