'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpLeft, ArrowLeft, Plus, Minus, ShoppingBag, X, Menu, Search, Check, Leaf, Package, Wheat, Truck, ShieldCheck, Building2, UtensilsCrossed, Hotel, ChefHat, MessageCircle, Trash2 } from 'lucide-react';
import CompanyProfile from './company-profile';
import { products as baseProducts, type Product } from './products';
import {getProducts,getCategories,translate,type Language} from './i18n';
import { buildWhatsAppUrl, makeOrderMessage, normalizeSearch, sanitizeCart } from './order';
function ProductImage({ product }: {
    product: Product;
}) { return <div role="img" aria-label={product.name} className="product-image" style={{ backgroundPosition: `${product.image % 6 * 20}% ${Math.floor(product.image / 6) * 20}%` }}/>; }
export default function Home() {
 const [language,setLanguage]=useState<Language>('ar');
 const t=(text:string)=>translate(text,language);
 const locale=language==='ar'?'ar-EG':'en-GB';
 const products=getProducts(language),categories=getCategories(language);
 useEffect(()=>{try{if(localStorage.getItem('oneva-language')==='en')setLanguage('en');}catch{}},[]);
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.title=language==='ar'?'ONEVA | شريك واحد لكل احتياجات التوريد':'ONEVA | One partner for every supply need';},[language]);
 function toggleLanguage(){const next=language==='ar'?'en':'ar';setLanguage(next);setNotice('');setError('');try{localStorage.setItem('oneva-language',next);}catch{}}
    const [category, setCategory] = useState('all'), [query, setQuery] = useState(''), [cart, setCart] = useState<Record<string, number>>({}), [ready, setReady] = useState(false), [menu, setMenu] = useState(false), [notice, setNotice] = useState(''), [error, setError] = useState(''), [name, setName] = useState(''), [business, setBusiness] = useState(''), [notes, setNotes] = useState(''), [phone, setPhone] = useState('');
    const dialog = useRef<HTMLDialogElement>(null), timer = useRef<ReturnType<typeof setTimeout> | null>(null);
    useEffect(() => { try {
        setCart(sanitizeCart(JSON.parse(localStorage.getItem('oneva-cart') || '{}')));
    }
    catch { } setReady(true); fetch('/site-config.json').then(r => r.json()).then((c: unknown) => setPhone(c && typeof c === 'object' && 'whatsappNumber' in c && typeof c.whatsappNumber === 'string' ? c.whatsappNumber : '')).catch(() => { }); return () => { if (timer.current)
        clearTimeout(timer.current); }; }, []);
    useEffect(() => { if (ready)
        try {
            localStorage.setItem('oneva-cart', JSON.stringify(cart));
        }
        catch { } }, [cart, ready]);
    const count = Object.values(cart).reduce((a, b) => a + b, 0), selected = products.filter(p => cart[p.id]), filtered = products.filter(p => (category === 'all' || p.category === category) && normalizeSearch(p.name + ' ' + p.origin + ' ' + baseProducts.find(b=>b.id===p.id)?.name + ' ' + getProducts('en').find(b=>b.id===p.id)?.name).includes(normalizeSearch(query)));
    function change(id: string, delta: number) { setCart(old => { const next = { ...old }, q = Math.min(999, Math.max(0, (next[id] || 0) + delta)); if (q)
        next[id] = q;
    else
        delete next[id]; return next; }); setError(''); }
    function add(p: Product) { change(p.id, 1); setNotice((t("تمت إضافة ") + p.name + t(" لطلبك"))); if (timer.current)
        clearTimeout(timer.current); timer.current = setTimeout(() => setNotice(''), 2300); }
    function openCart() { setError(''); dialog.current?.showModal(); document.body.style.overflow = 'hidden'; }
    function closeCart() { dialog.current?.close(); document.body.style.overflow = ''; }
    function contact() { const url = buildWhatsAppUrl(phone, t("مرحباً ONEVA، أود الاستفسار عن خدمات التوريد وعروض الأسعار.")); if (url)
        window.open(url, '_blank', 'noopener,noreferrer');
    else {
        openCart();
        setError(t("سيتم تفعيل التواصل قريباً. رقم واتساب لم يُضف بعد."));
    } }
    function checkout() { if (!selected.length)
        return; const url = buildWhatsAppUrl(phone, makeOrderMessage(cart, { name, business, notes }, language)); if (!url) {
        setError(t("استقبال الطلبات غير مفعّل حالياً. يُرجى المحاولة بعد إضافة رقم واتساب الخاص بالشركة."));
        return;
    } window.open(url, '_blank', 'noopener,noreferrer'); }
    useEffect(() => { const context = (document as any).modelContext; if (!context?.registerTool)
        return; const lifecycle = new AbortController(); try {
        Promise.resolve(context.registerTool({ name: 'stage_supply_order', description: 'Stage product IDs and quantities in the visible local basket. Does not send an order.', inputSchema: { type: 'object', properties: { items: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, quantity: { type: 'integer', minimum: 1, maximum: 999 } }, required: ['id', 'quantity'], additionalProperties: false } } }, required: ['items'], additionalProperties: false }, annotations: { readOnlyHint: false }, execute(input: any) { if (!Array.isArray(input?.items) || !input.items.length || input.items.some((i: any) => !products.some(p => p.id === i.id) || !Number.isInteger(i.quantity) || i.quantity < 1 || i.quantity > 999))
                throw Error('Invalid products or quantities'); setCart(old => ({ ...old, ...Object.fromEntries(input.items.map((i: any) => [i.id, i.quantity])) })); return { staged: input.items.length, sent: false }; } }, { signal: lifecycle.signal })).catch(() => { });
    }
    catch { } return () => lifecycle.abort(); }, []);
    return <>
 <a className="skip-link" href="#main">{t("انتقل للمحتوى")}</a><div className="topbar"><span>{t("شريك توريد واحد. قيمة تدوم.")}</span><span dir="ltr">B2B PROCUREMENT & OPERATIONAL SUPPLY</span></div>
 <header className="header"><div className="container nav"><a href="#" className="logo" aria-label={t("ONEVA الرئيسية")}><img src="/logo.svg" alt="ONEVA" width="158" height="43"/></a><nav aria-label={t("القائمة الرئيسية")} className={menu ? 'links open' : 'links'}>{[['#', t("الرئيسية")], ['#about', t("عن ONEVA")], ['#services', language==='ar'?'خدماتنا':'Services'], ['#categories', t("قطاعات التوريد")], ['#shop', t("المنتجات")], ['#process', t("كيف نعمل")]].map(([url, label]) => <a key={label} href={url} onClick={() => setMenu(false)}>{label}</a>)}</nav><div className="nav-actions"><button className="language-switch" type="button" onClick={toggleLanguage} aria-label={language==='ar'?'Switch to English':'التبديل إلى العربية'} lang={language==='ar'?'en':'ar'}><span aria-hidden="true">◎</span>{language==='ar'?'English':'العربية'}</button><button className="cart-trigger" onClick={openCart} aria-label={(t("سلة الطلب، ") + count + t(" وحدة"))}><ShoppingBag size={20}/><span className="cart-label">{t("طلبك")}</span><b>{count.toLocaleString(locale)}</b></button><button className="menu-trigger" onClick={() => setMenu(!menu)} aria-label={t("القائمة")} aria-expanded={menu}>{menu ? <X /> : <Menu />}</button></div></div></header>
 <main id="main"><section className="hero"><div className="container hero-layout"><div className="hero-copy"><div className="eyebrow"><span />{t(" توريد منظّم. أعمال مستمرة.")}</div><h1>{t("كل احتياجاتك.")}<br />{t("شريك ")}<em>{t("واحد.")}</em></h1><p>{t("من أجود التوابل إلى مستلزمات التشغيل، نجمع احتياجات أعمالك في مكان واحد. جودة ثابتة وتوريد منتظم، لتتفرّغ لما تصنعه أفضل.")}</p><div className="hero-actions"><a className="button gold" href="#shop">{t("تصفّح المنتجات ")}<ArrowUpLeft size={21}/></a><a className="text-link" href="#about">{t("تعرّف على ONEVA ")}<ArrowLeft size={19}/></a></div><div className="hero-foot"><span><ShieldCheck size={19}/>{t(" جودة بمواصفات واضحة")}</span><span><Truck size={20}/>{t(" توريد حسب احتياجك")}</span></div></div><div className="hero-visual"><img className="hero-photo" src="/hero.webp" alt={t("تشكيلة من التوابل والحبوب المختارة للتوريد")} fetchPriority="high"/><div className="photo-label"><span className="label-icon"><Leaf size={26}/></span><div><small>{t("مختارة بعناية لأعمالك")}</small><strong>{t("جودة تبدأ من المصدر.")}</strong></div><span className="label-arrow">↖</span></div><div className="visual-caption" dir="ltr"><span>ONE SOURCE. ENDLESS POSSIBILITIES.</span><span>01 / 04</span></div></div></div><div className="hero-outline" aria-hidden="true">O</div></section>
 <div className="sectors-strip"><div className="container"><span>{t("نلبّي احتياجات")}</span><span><UtensilsCrossed />{t(" المطاعم")}</span><span><Hotel />{t(" الفنادق والمنتجعات")}</span><span><ChefHat />{t(" شركات الكاترينج")}</span><span><Building2 />{t(" المؤسسات")}</span><span><Package />{t(" المطابخ المركزية")}</span></div></div>
 <section className="section container" id="categories"><div className="section-heading"><div><div className="eyebrow dark">{t("مجالات التوريد")}</div><h2>{t("احتياجات متنوعة.")}<br className="mobile-break"/>{t(" مصدر واحد.")}</h2></div><p>{t("أربع فئات أساسية، تحت مظلة توريد واحدة.")}<br />{t("اختر ما يحتاجه عملك ودع الباقي علينا.")}</p></div><div className="category-grid">{categories.map((c, i) => { const Icon = [Leaf, Wheat, Leaf, Package][i]; return <a className="category-card" href="#shop" key={c.id} onClick={() => { setCategory(c.id); setQuery(''); }}><div className="category-icon"><Icon size={28}/></div><small>0{i + 1}</small><h3>{c.name}</h3><p>{c.description}</p><div className="category-bottom"><span>{products.filter(p => p.category === c.id).length.toLocaleString(locale)}{t(" منتج")}</span><ArrowUpLeft size={22}/></div></a>; })}</div></section>
 <section className="about-section" id="about"><div className="container about-layout"><div className="about-brand"><img src="/brand-mark.png" alt={t("رمز ONEVA")}/><span dir="ltr">ONE VENDOR.<br /><em>ONE VALUE.</em></span></div><div className="about-copy"><div className="eyebrow dark">{t("عن ONEVA")}</div><h2>{t("شريك في تشغيل أعمالك،")}<br />{t("من أول طلب.")}</h2><p>{t("ONEVA شركة مصرية متخصصة في المشتريات والتوريد التشغيلي للشركات. نختصر تشتّت التعامل مع موردين متعددين في علاقة واحدة منظّمة، تجمع الجودة والقيمة والمتابعة.")}</p><div className="about-points"><span><Check />{t(" مواصفات واضحة قبل التوريد")}</span><span><Check />{t(" أسعار تناسب حجم أعمالك")}</span><span><Check />{t(" مواعيد توريد متفق عليها")}</span><span><Check />{t(" نقطة تواصل واحدة")}</span></div></div></div></section>
 <CompanyProfile language={language} onContact={contact}/><section className="section container shop-section" id="shop"><div className="section-heading"><div><div className="eyebrow dark">{t("كتالوج المنتجات")}</div><h2>{t("اختياراتك. بداية طلبك.")}</h2></div><div className="shop-heading-note"><MessageCircle size={22}/><span>{t("اختر المنتجات والكميات")}<br /><strong>{t("واطلب عرض سعر عبر واتساب")}</strong></span></div></div><div className="shop-controls"><div className="tabs" role="group" aria-label={t("فئات المنتجات")}><button aria-pressed={category === 'all'} className={category === 'all' ? 'active' : ''} onClick={() => setCategory('all')}>{t("كل المنتجات ")}<span>{t("٤١")}</span></button>{categories.map(c => <button key={c.id} aria-pressed={category === c.id} className={category === c.id ? 'active' : ''} onClick={() => setCategory(c.id)}>{c.short}</button>)}</div><label className="search"><Search size={19}/><input placeholder={t("ابحث عن منتج...")} aria-label={t("ابحث عن منتج")} value={query} onChange={e => setQuery(e.target.value)}/>{query && <button aria-label={t("مسح البحث")} onClick={() => setQuery('')}><X size={16}/></button>}</label></div><div className="results-meta"><span aria-live="polite">{t("عرض ")}{filtered.length.toLocaleString(locale)}{t(" منتج")}</span><span>{t("الأسعار حسب الكمية والمواصفات")}</span></div>
 <div className="product-grid">{filtered.map(p => <article className="product-card" key={p.id}><div className="product-image-wrap"><ProductImage product={p}/><span className="product-tag">{p.origin}</span>{cart[p.id] > 0 && <span className="selected-mark" aria-label={t("مضاف للطلب")}><Check size={15}/></span>}</div><div className="product-info"><small>{categories.find(c => c.id === p.category)?.short}</small><h3>{p.name}</h3><p>{p.pack || t("الكمية والتعبئة حسب احتياجك")}</p><div className="product-bottom"><span>{t("حسب عرض السعر")}</span>{cart[p.id] ? <div className="quantity-control"><button aria-label={(t("زيادة ") + p.name + "")} onClick={() => change(p.id, 1)} disabled={cart[p.id] >= 999}><Plus size={16}/></button><span aria-live="polite">{cart[p.id]}</span><button aria-label={(t("تقليل ") + p.name + "")} onClick={() => change(p.id, -1)}><Minus size={16}/></button></div> : <button className="add-button" onClick={() => add(p)}><Plus size={16}/>{t(" أضف للطلب")}</button>}</div></div></article>)}</div>{!filtered.length && <div className="empty-results"><Search size={36}/><h3>{t("لم نجد منتجاً بهذا الاسم")}</h3><p>{t("جرّب كلمة أخرى أو تصفّح كل المنتجات.")}</p><button className="button green" onClick={() => { setQuery(''); setCategory('all'); }}>{t("عرض كل المنتجات")}</button></div>}<p className="image-note">{t("الصور توضيحية. يتم تأكيد المنشأ والمواصفات والتعبئة والتوفّر عند إعداد عرض السعر.")}</p></section>
 <section className="process-section section" id="process"><div className="container"><div className="section-heading"><div><div className="eyebrow dark">{t("من الاختيار إلى التوريد")}</div><h2>{t("طلبك أبسط مما تتخيّل.")}</h2></div><p>{t("خطوات واضحة، وفريق يتابع معك التفاصيل.")}</p></div><div className="steps">{[{ n: '01', title: t("اختر احتياجاتك"), desc: t("تصفّح الكتالوج وأضف الأصناف والكميات إلى طلبك."), Icon: ShoppingBag }, { n: '02', title: t("أرسل على واتساب"), desc: t("راجع طلبك وأضف تفاصيل أعمالك وأي مواصفات خاصة."), Icon: MessageCircle }, { n: '03', title: t("استلم عرض السعر"), desc: t("نراجع معك الكميات والمواصفات والتوفّر والتكلفة."), Icon: ShieldCheck }, { n: '04', title: t("نتفق ونورّد"), desc: t("نؤكد تفاصيل الطلب وجدول التوريد المناسب لتشغيلك."), Icon: Truck }].map(({ n, title, desc, Icon }) => <div className="step" key={n}><div className="step-top"><span>{n}</span><Icon size={25}/></div><h3>{title}</h3><p>{desc}</p></div>)}</div></div></section>
 <section className="contact-section"><div className="container contact-layout"><div><div className="eyebrow">{t("نبدأ علاقة توريد أفضل")}</div><h2>{t("خلّي تركيزك على أعمالك.")}<br /><em>{t("واحتياجاتك علينا.")}</em></h2><p>{t("طلب واحد أو توريد دوري، نتحدث معك لنفهم ما تحتاجه.")}</p></div><button className="button gold" onClick={contact}>{t("تحدث مع فريق ONEVA ")}<MessageCircle size={21}/></button></div></section></main>
 <footer><div className="container footer-main"><a href="#" className="logo"><img src="/logo.svg" alt="ONEVA" width="166" height="45"/></a><p>{t("شريكك للمشتريات والتوريد التشغيلي في مصر.")}</p><div><a href="#about">{t("عن الشركة")}</a><a href="#shop">{t("المنتجات")}</a><button onClick={contact}>{t("تواصل معنا")}</button></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()}{t(" ONEVA. جميع الحقوق محفوظة.")}</span><span dir="ltr">One Vendor. One Value.</span></div></footer>
 {count > 0 && <button className="floating-cart" onClick={openCart}><ShoppingBag size={21}/><span>{t("مراجعة طلبك")}</span><b>{selected.length.toLocaleString(locale)}{t(" أصناف")}</b><ArrowLeft size={19}/></button>}<div role="status" className={`toast ${notice ? 'show' : ''}`}><Check size={18}/>{notice}</div>
 <dialog ref={dialog} className="cart-dialog" aria-labelledby="cart-title" onClose={() => { document.body.style.overflow = ''; }} onClick={e => { if (e.target === e.currentTarget)
        closeCart(); }}><div className="cart-panel"><div className="cart-header"><div><div className="eyebrow dark">{t("عرض سعر مخصص لأعمالك")}</div><h2 id="cart-title">{t("طلب التوريد ")}<span>({selected.length})</span></h2></div><button className="icon-button" onClick={closeCart} aria-label={t("إغلاق الطلب")}><X /></button></div><div className="cart-body">{selected.length ? <><p className="cart-explainer">{t("راجع الكميات وأرسل طلبك. سيؤكد فريقنا الأسعار والتوفّر معك عبر واتساب.")}</p><div className="cart-items">{selected.map(p => <div className="cart-item" key={p.id}><ProductImage product={p}/><div className="cart-item-copy"><h3>{p.name}</h3><small>{p.unit}{p.pack ? ` · ${p.pack}` : ''}</small><div className="quantity-control"><button aria-label={(t("زيادة كمية ") + p.name + "")} onClick={() => change(p.id, 1)} disabled={cart[p.id] >= 999}><Plus size={16}/></button><input type="number" min="1" max="999" value={cart[p.id]} aria-label={(t("كمية ") + p.name + "")} onChange={e => { const v = Number(e.target.value); if (Number.isInteger(v) && v >= 1 && v <= 999)
        setCart(old => ({ ...old, [p.id]: v })); }}/><button aria-label={(t("تقليل كمية ") + p.name + "")} onClick={() => change(p.id, -1)}><Minus size={16}/></button></div></div><button className="remove-button" aria-label={(t("حذف ") + p.name + "")} onClick={() => setCart(old => { const next = { ...old }; delete next[p.id]; return next; })}><Trash2 size={18}/></button></div>)}</div><div className="customer-fields"><h3>{t("تفاصيل إضافية ")}<small>{t("اختياري")}</small></h3><label>{t("اسمك")}<input autoComplete="name" value={name} maxLength={100} onChange={e => setName(e.target.value)} placeholder={t("الاسم")}/></label><label>{t("اسم الشركة أو النشاط")}<input autoComplete="organization" value={business} maxLength={150} onChange={e => setBusiness(e.target.value)} placeholder={t("اسم المطعم، الفندق أو الشركة")}/></label><label>{t("ملاحظات الطلب")}<textarea rows={3} value={notes} maxLength={1200} onChange={e => setNotes(e.target.value)} placeholder={t("مكان التوريد، الموعد المطلوب، أو مواصفات وتعبئة خاصة...")}/></label></div></> : <div className="empty-cart"><ShoppingBag size={48}/><h3>{t("طلبك يبدأ باختيارك")}</h3><p>{t("أضف المنتجات التي يحتاجها عملك من الكتالوج.")}</p><a className="button green" href="#shop" onClick={closeCart}>{t("تصفّح المنتجات ")}<ArrowLeft size={18}/></a></div>}</div><div className="cart-footer">{error && <p className="form-error" role="alert">{error}</p>}<button className="button green checkout" disabled={!selected.length} onClick={checkout}><MessageCircle size={22}/>{t(" إرسال الطلب عبر واتساب ")}<ArrowUpLeft size={20}/></button><p>{t("طلب عرض سعر فقط — يتم تأكيد الطلب بعد الاتفاق.")}</p></div></div></dialog>
 </>;
}
